version: '3'
services:
  app:
    container_name: docker-node-mongo
    restart: always
    build: .
    ports:
      - '${PORT}:3000'
    environment:
      - PORT
    links:
      - mongo  
  mongo:
    container_name: mongo
    image: mongo
    ports:
      - '27017:27017'
    environment:
      MONGO_INITDB_DATABASE: '$MONGO_INITDB_DATABASE'
